name: Test
on: [push]
jobs:
  linux-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Terminus on *nix
        uses: ./
        with:
          os: ubuntu-latest
  macos-test:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with: 
          php-version: 8.3        
      - name: Install Terminus on macOS
        uses: ./
        with:
          os: macos-latest